---
title: "Module 11"
author: "Patricia McGee"
date: '2022-04-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The Instructions

The code below contains a 'deliberate' bug!  

tukey_multiple <- function(x) {
   outliers <- array(TRUE,dim=dim(x))
   for (j in 1:ncol(x))
    {
    outliers[,j] <- outliers[,j] && tukey.outlier(x[,j])
    }
outlier.vec <- vector(length=nrow(x))
    for (i in 1:nrow(x))
    { outlier.vec[i] <- all(outliers[i,]) } return(outlier.vec) }

> Find the bug and fix it.
>>Report on your blog the success or failure in your debugging procedure.

## My Code and Thoughts

First step is to run the code as is and see what errors it gives us.

```{r debugging, echo=TRUE}

tukey_multiple <- function(x) {
   outliers <- array(TRUE,dim=dim(x))
   for (j in 1:ncol(x)){
      outliers[,j] <- outliers[,j] # && tukey.outlier(x[,j])
      }
    outlier.vec <- vector(length=nrow(x))
    for (i in 1:nrow(x)){ 
      outlier.vec[i] <- all(outliers[i,]) 
      } 
    return(outlier.vec)
    }

tukey_multiple(mtcars)

```


